### ISSUE TITLE
Is rowHeight deprecated?

### ISSUE THREAD

**Issue by leventkantaroglu** [ech89899/spannablegrid-flutter#7]
Hello,

`rowHeight` parameter is currently undefined. 
And there is no log for this on changelog file.

What is the solution for this parameter?
Thanks

**Comment by echedev** [comment]
Hi @leventkantaroglu,
Yes, `rowHeight` parameter removed. Sorry for not enough details in changelog, though the latest record there is marked as 'BREAKING' 😄 
You can use `gridSize` instead. Set `SpannableGridSize.parent` value for `gridSize`, and provide required constraints for grid widget (for example by wrapping it in SizedBox with proper width and height).

**Comment by leventkantaroglu** [comment]
Thanks, I will try it 👍
